on:
  push:
    tags: ["*"]

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: apt-update
        if: startsWith(matrix.os, 'ubuntu-latest')
        run: sudo apt-get update

      - name: autoremove
        if: startsWith(matrix.os, 'ubuntu-latest')
        run: sudo apt autoremove

      - name: Install system dependencies
        if: startsWith(matrix.os, 'ubuntu-latest')
        run: sudo apt-get install -y build-essential python3 gcc g++ make libarchive-tools rpm

      - name: Release Electron app for Ubuntu
        if: startsWith(matrix.os, 'ubuntu-latest')
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          release: true
          args: --linux deb

      - name: Release Electron app for Mac
        if: startsWith(matrix.os, 'macos-latest')
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          release: true
          args: --mac

      - name: Release Electron app for Windows
        if: startsWith(matrix.os, 'windows-latest')
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          release: true
          args: --win