on:
  push:
    tags: ["*"]

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: apt-update
        run: sudo apt-get update

      - name: autoremove
        run: sudo apt autoremove

      - name: Install libarchive rpm on Linux
        run: sudo apt-get install libarchive-tools rp

      - name: Release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          release: true
          